### ISSUE TITLE
${workspaceFolder} in behave settings.json does not get resolved when running w/o debugger

### ISSUE THREAD

**Issue by schwaerz** [jimasp/behave-vsc#31]
**Describe the bug (required):**
I have a behave set-up where I need to set some environment variables from within the workspace's `settings.json`, like
```json
    "behave-vsc.envVarOverrides": {
        "MY_PATH": "${workspaceFolder}/path/to/my/tool",
    }
```

This works fine when I run the tests from within the debugger.
If I just run the tests in without the debugger, `${workspaceFolder}` will not get resolved. Did some logging to ensure that this is the case. The environment variable will be like:

```
assert os.environ.get("MY_PATH") == "${workspaceFolder}/path/to/my/tool"
```

I would expect that `${workspaceFolder}` will get resolved, e.g.:
```
assert os.environ.get("MY_PATH") == "/path/to/workspace/path/to/my/tool"
```

**To Reproduce (required):**
Try passing a simple environment variable to behave using the `envVarOverrides`. Within the `envVarOverrides`, reference ${workspaceFolder}.

Unfortunetaly I do not have a public repo available, if it cannot be reproduced on your end, I'll try to make one.

**Operating system (required):**
Running inside a devcontainer (Ubuntu 20.04) inside WSL (Ubuntu 22.04).

Please let me know in case more information is required.

**Comment by schwaerz** [comment]
btw.: As a workaround, I am using now:
```json
    "behave-vsc.envVarOverrides": {
        "MY_PATH": "path/to/my/tool",
    }
```

Seems to work fine. However I feel this should be looked into, esp. as of the different behaviour with running with and w/o the debugger.

**Comment by jimasp** [comment]
Extensions use the vscode API vscode.WorkspaceConfiguration object to read settings.json
i.e. the extension is not responsible for replacing the value.

It looks like this is a vscode bug that's been raised a few times:
https://github.com/microsoft/vscode/issues/140056

It would be possible to hard code in support for ${workspaceFolder}, but obviously that wouldn't work for any other vscode variable and could be error-prone in case the MS implementation changes.

It's curious that the replacement works for debugging a test, because when I debug the extension code, I only ever see "${workspaceFolder}" returned from the vscode API. 

I'll leave this issue open for now, but really I think it needs an MS fix.

**Comment by schwaerz** [comment]
Most probably it is. I do not have a lot of know-how writing VSCode extensions, but your explanation totally makes sense to me. Thanks for the quick response 👍
