### ISSUE TITLE
Tests running in parallel despite `runParallel` = `false`

### ISSUE THREAD

**Issue by schwaerz** [jimasp/behave-vsc#32]
**Describe the bug (required):**
We have a bunch of tests configured which rely on opening some TCP port for testing.
When running all tests, I can see in VSCode that all tests seem to be triggered in parallel. Also, some of the tests would fail claiming that the port is already in use.

Therefore I believe the the tests are still somehow running in parallel despite the setting in settings.json
```json
    "behave-vsc.runParallel": false
```

It does not seem to make any difference whether this is set to `true` or `false` or not set at all.

**To Reproduce (required):**
To reproduce the issue, please run some behave tests in VSCode which need to use the same resource (e.g. opening a file).
Try running all tests with one click, supplying different values to `runParallel`.

If it is hard to reproduce, I will try to come up with some example.

**Operating system (required):**
Ubuntu 20.04 (dev container) from within Ubuntu 20.04 running inside WSL2 on Win11.

**Comment by jimasp** [comment]
I think a lot of people would be complaining if this was a common problem. So it must be something about your setup. I could not recreate it.

_When running all tests, if the extension is running in parallel mode, you will see multiple behave commands output in the Behave VSC output window. If it is not in parallel mode you will see a single behave command_.

Have you tried running the exact command that is output in Behave VSC output window? i.e. from the command line _without_ using the extension - what happens? do you get the same problem?

**Comment by schwaerz** [comment]
I tried to reproduce with a simple setup, could not :(
I will have to have a closer look into it. Thanks for the quick response. Probably something strange at our end.

**Comment by jimasp** [comment]
could not recreate

**Comment by bigjohn98pl** [comment]
I think i have the same issue as @schwaerz 

![Image](https://github.com/user-attachments/assets/4181224b-b9e8-49b3-bad3-9ad6e341afe3)

On the screenchoot we see folder that have  .feature file and the rest are test scenarios in that one .feature file.
I  have this behavior when I click on a folder to run all  test scenarios in that folder. When all of test scenarios are executed in the file  then the status of the file and for the all scenarios is change in the same time form "in progress" to "Passed"  or "Failed". So it's looks like the problem is with Scenarios interpretation.
 
Operating system:
Windows 11 Enterprise
24H2
Windows Feature Experience 1000.26100.66.0

VSC  version:
Version: 1.99.3 (user setup)
Commit: 17baf841131aa23349f217ca7c570c76ee87b957
Date: 2025-04-15T23:18:46.076Z
Electron: 34.3.2
ElectronBuildId: 11161073
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by jimasp** [comment]
@bigjohn98pl 
>all scenarios is change in the same time form "in progress" to "Passed" or "Failed

Behave does not write the results of feature execution to disk until the feature has finished executing.
The extension then reads that file.
(If `behave-vsc.runParallel` is `true` then the features will be run in parallel, NOT the scenarios.)
