### ISSUE TITLE
Problem with multi-line scenario name

### ISSUE THREAD

**Issue by dmateja** [jimasp/behave-vsc#36]
**Describe the bug (required):**
For multi-line scenario names where the first line is the same in two or more scenarios, the Behave-VCS reports:
"Error: Attempted to insert a duplicate test item ID..."
Since our scenario names are long, we often split them into 2 lines.
Version 0.6.1

**To Reproduce (required):**
Just copy to feature:
`
Scenario: Multi-line scenario name
the second line of 1

Scenario: Multi-line scenario name
the second line of 2
`

**Operating system (required):**
Windows

Best regards

**Comment by jimasp** [comment]
Your example, while valid Gherkin syntax, is not a multi-line scenario title.

---

1. Gherkin does not support multi-line scenario titles (or multi-line feature titles).
Lines that follow certain keywords (including `Feature`/`Scenario` are considered to be descriptive text, not part of the title.

    You can find the official Gherkin language specification on the Cucumber website at 
    https://cucumber.io/docs/gherkin/reference/. 
    This states that "Free-form descriptions (as described above for Feature) can also be placed underneath 
    Example/Scenario, Background, Scenario Outline and Rule."

    i.e. the text "the second line of 1" in your example is descriptive text, it is not part of the scenario title.
---

2. I'm curious how you run a single scenario from this feature using the behave command line?

   In theory, for this:
```
Feature: My feature

	Scenario: Multi-line scenario name
		the second line of 1
		Given we have behave installed
		When we implement a successful test
		Then we will see the result

	Scenario: Multi-line scenario name
		the second line of 2
		Given we have behave installed
		When we implement a successful test
		Then we will see the result
```

   The command might look something like this, but I wouldn't expect behave to support it:
```
"/bin/python3" -m behave "features/myfeature.feature" -n "Multi-line scenario name\n\t\tthe second line of 1"
```
---

3. If you run the entire feature:
```
"/bin/python3" -m behave "features/myfeature.feature"
```

   The output would be something like this because behave would not recognise the multi-line titles as different:
```
Feature: My feature # features/myfeature.feature:1

  Scenario: Multi-line scenario name    # features/myfeature.feature:3
    ...

  Scenario: Multi-line scenario name    # features/myfeature.feature:9
    ...
```

    i.e. the extended title would not show in the BDD output.
    This breaks the BDD concept because the meaning is lost between the two scenarios.

---

There is arguably a small bug here in that after raising the error, the extension should probably add the first scenario and just ignore the duplicate.
But fixing that would not allow you to run each scenario separately. You could just run the entire feature, and the BDD output would still not make sense.
Really you need to have distinct one-line scenario titles if you want your output to make sense.

**Comment by dmateja** [comment]
Ups... sorry.
I usually check the output on Jenkins from our tests... Now I'm testing Your tools and... I was in a hurry, sorry.
I will create a ticket to remove autoformatting feature files in our test environment (or to use shorter scenario names :) ).
