### ISSUE TITLE
No JUnit file was written for this test. Check output in Behave VSC output window.

### ISSUE THREAD

**Issue by thedayofcondor** [jimasp/behave-vsc#48]
Hi,
using the latest preview I get this error when running a test:

`No JUnit file was written for this test. Check output in Behave VSC output window.`

Looking at the Behave VSC output window the test runs and it passes. The command line the extension uses includes `--junit --junit-directory "/tmp/behave-vsc/junit/185800/asset"` which, after the test completes, contains the junit file `TESTS-connectivity.xml`

This was working before with the same extension version, so it is possible something else has changed in my system, but I am stuck...

**Comment by jimasp** [comment]
Not sure what you mean by "latest preview", but:
- the extension seems to work ok on the latest vscode 1.87.0 and the latest vscode insiders build 1.88.0
- i assume you are using behave 1.2.6? (1.2.7 is not supported atm)
- the extension hasn't changed since October (but bear in mind that when you update vscode itself, that can update extensions to newer versions without you asking unless you specifically turn that option off)

"No JUnit file was written for this test" simply means that the extension couldn't find the _expected_ junit file, i.e. the name that behave created for the junit file wasn't the one the extension expected.
(The next version of the extension (0.7.0) addresses that, but it's still being tested. I'm hoping to get it published in the next 2-4 weeks.)

On the plus side, none of this should stop you from working. 
You can still debug/run the test, it just shows wrong in the UI.

Obviously the quick fix would be to revert whatever you've changed.
Perhaps you have moved files around or renamed something that has affected the output filename? or you have changed your behave.ini?
Does it work if you go back to an older version of your source code?

**Comment by thedayofcondor** [comment]
Hi,
thank you for the reply - sorry I mean the latest pre-release, 0.6.4. 

I don't think it is an issue with the extension, as it hasn't changed in months (and I tried to revert to the version before that but doesn't make a difference). Unfortunately the error message is rather generic.

I am using behave 1.2.6. 

So - everything points to something changed on my system (I am running Linux and I regularly install updates), it could also be something in my repo (never thought to check if someone in my team has changed behaverc ) as another of our developers mentioned having the same issue.

I never thought the extension may be looking for a specific file rather than a generic *.xml in the junit output folder (as the error message doesn't mention anything specific).

And yes - I can still use the extension (and I do) it's just annoying :) but the extension is still invaluable (and the best of his kind)

I will do some more digging, if I found the issue/a solution I will post it here for posterity!

**Comment by jimasp** [comment]
I think the first thing you should try is reverting your source code to an older version just to see what happens. 
The things most likely to affect the behave file name are the relative features folder location and name, behave.ini/behaverc "paths", and the settings.json "behave-vsc.featuresPath".

Otherwise, if you really want a fix right now, then an alternative is to uninstall 0.6.4 and try installing the vsix in the attached zip.
This is a very early preview build of 0.7.0. While this is passing all automated tests, it has not been manually tested, may contain bugs, have incorrect documentation, may have features removed in future, and is currently broken on windows, but it will probably fix your current issue until there is a proper release of 0.7.0.
(It's currently tied to vscode >1.86.0.)
If you do try it, please let me know if it solves your issue.

[0.7.0-pre-alpha.zip](https://github.com/jimasp/behave-vsc/files/14458623/0.7.0-pre-alpha.zip)

**Comment by thedayofcondor** [comment]
I tried debugging 0.6.4 but it is minified, i should rebuild it from source but it is too much work considering I am not familiar with the setup.

I am trying 0.7.0 you sent, but there is an issue, I am getting a lot of:

```
ENOENT: no such file or directory, stat '<<<my workspace filename>>>' at statSync (node:fs:1692:3) at Object.statSync (node:electron/js2c/node_init:2:4795) at ...
```
stopping the extension on its tracks. This is because my repo has a lot of invalid symlinks (pointing to files that do not exist yet)

**Comment by thedayofcondor** [comment]
Past that, 0.7.0 solves the problem:

![image](https://github.com/jimasp/behave-vsc/assets/44357327/9932899b-0912-46ee-8098-f1823d94904b)

**Comment by thedayofcondor** [comment]
I also found the problem with 0.6.4 - a developer has changed `.behaverc`, from  `paths=test/bdd/` to `paths=test/bdd/features` - that does not create any problem in `behave` itself, but reverting it fixes the issue with the JUnit file not being found by the extension.

I have `"behave-vsc.featuresPath": "test/bdd/features` in the config.

**Comment by jimasp** [comment]
makes sense. 
0.7.0 works differently because it no longer uses "featuresPath" but instead goes directly to your behave config file so that it can determine paths and junit filenames in the same way as behave.

**Comment by jimasp** [comment]
btw, i expect what you will notice is that when you change the behaverc file it changes the name of the junit file.

**Comment by thedayofcondor** [comment]
Yes you are right.

`paths=test/bdd/` -> `TESTS-features.connectivity.xml`

`paths=test/bdd/features` -> `TESTS-connectivity.xml`

That was definitely the issue. 

I cannot see anything in the behave documentation telling me if paths should point to the features folder or its parent, behave seems to accept both.

However I understand that should match what I have in `"behave-vsc.featuresPath"` (and this step is not needed anymore in 0.7.0), but in 0.6.4 what I have in `"behave-vsc.featuresPath"` seems irrelevant, as it was already matching `paths`. 

But now everything is working, thank you very much for your time! 

I am looking forward to 0.7.0 :smile:

**Comment by inmaso** [comment]
We are using behave-vsc v0.6.4 with behave 1.2.7.dev6 and found a similar issue. We did not have a `.behaverc` file, so we created it on the project root pointing to the features folder, so the contents were:
```
[behave]
paths=tests/features
```
for our specific directory structure

Hopefully this will help others with resolving this issue! Thanks @jimasp for the plugin and @thedayofcondor for your helpful thread
